### ISSUE TITLE
TC035: Verificar el Ícono del Ojo para Visualizar la Contraseña

### ISSUE THREAD

**Issue by TauTech99** [ISPC-2024-GrupoEstudio/GrupoEstudio-Mobile2024#128]
#38

**Comment by TauTech99** [comment]
@MilenaGimenez 
**Reporte de Bug 003**
ID del Bug: BUG-TC035-003
Título: El ícono del ojo para visualizar la contraseña no está implementado.
Severidad: Media
Prioridad: Alta
Estado: Abierto
Versión Afectada: v1.0
Fecha del Informe: 30/10/2024
Reportado por: Taoufik Saidi

**Descripción del Problema:**
Al intentar usar el ícono del ojo en el campo de contraseña para alternar entre mostrar y ocultar la contraseña, se detectó que el ícono no está implementado. Esta falta afecta la experiencia del usuario al no permitirle verificar visualmente la contraseña mientras la escribe.

**Pasos para Reproducir:**

1. Iniciar la aplicación móvil Pet Boutique.
2. Navegar a la pantalla de Inicio de Sesión 
3. Localizar el campo Contraseña.
4. Intentar encontrar el ícono de ojo junto al campo de contraseña.
5. Comprobar si el ícono está presente y permite alternar la visibilidad de la contraseña.

**Resultado Esperado:**
El ícono del ojo debería estar visible junto al campo de contraseña.
Al hacer clic en el ícono, la contraseña debería mostrarse en texto claro.
Al hacer clic nuevamente, la contraseña debería ocultarse con puntos o asteriscos.
Resultado Real:
El ícono del ojo no está presente en la pantalla, impidiendo al usuario alternar entre mostrar y ocultar la contraseña.

**Evidencia**:
![ojo de visualizacion](https://github.com/user-attachments/assets/d0a86d38-8e01-4c4b-a1f6-ce7161511375)

**Entorno**:
Sistema Operativo: Android 14
Versión de la App: v1.0
Dispositivo: Samsung Galaxy S10
Conexión: Wi-Fi

**Posible Impacto:**

- **La ausencia de esta funcionalidad puede provocar errores de ingreso de contraseña, lo que podría generar frustración en los usuarios.**
- **Afecta la usabilidad del proceso de autenticación al no permitir que el usuario verifique su contraseña.**

**Etiquetas**:
#Funcional
#Usabilidad
#UI
#PasswordVisibility
#ManualTesting
#Seguridad 

**Comentarios:**
Este problema podría ser resultado de un olvido en la implementación del ícono en el frontend o de un fallo en los eventos asociados al botón de visibilidad. Se recomienda revisar el diseño y los scripts del campo de contraseña para asegurar que el ícono se implemente correctamente y funcione según lo esperado.

**Comment by MilenaGimenez** [comment]
*Informe de Resolución de Bug 003*
ID del Bug: BUG-TC035-003
Título: El ícono del ojo para visualizar la contraseña no estaba implementado.
Estado: Cerrado
Fecha de Resolución: 02/11/24
Resuelto por: Milena Gimenez

*Descripción del Problema:*
El ícono del ojo que permite alternar entre mostrar y ocultar la contraseña no estaba presente en la pantalla de inicio de sesión. Esto afectaba la usabilidad y la experiencia del usuario durante el proceso de autenticación.

*Causa Raíz:*
Se identificó que el componente del ícono no fue implementado en el frontend durante la fase de desarrollo inicial. La funcionalidad no estaba incluida en el código relacionado con la interfaz del campo de contraseña.

*Acciones Tomadas:*
Implementación del Ícono: Se agregó el ícono del ojo al campo de contraseña en la pantalla de inicio de sesión.
Asignación de Eventos: Se implementaron los eventos de clic para alternar entre mostrar y ocultar la contraseña.
Pruebas Manuales: Se realizaron pruebas manuales para verificar que la funcionalidad se comporta según lo esperado.
Pruebas de Revisión: El equipo de QA validó el caso utilizando la API de pruebas.

*Resultados de la Prueba:*
Caso Positivo:
Al hacer clic en el ícono de ojo, la contraseña se muestra en texto claro.
Al volver a hacer clic, la contraseña se oculta nuevamente como puntos o asteriscos.
Caso Negativo:
Se verificó que la visibilidad de la contraseña no permanece activa por defecto.
Al recargar la pantalla, la contraseña permanece oculta por seguridad.

*Evidencia:*
Se adjunta captura de pantalla que muestra el comportamiento esperado del ícono del ojo y su correcta implementación.
![Image](https://github.com/user-attachments/assets/d1d33bd2-67e3-4d1a-9d54-f73b0fb09db7)



*Entorno de Prueba:*
Sistema Operativo: Android 14
Versión de la App: v1.0
Dispositivo: Samsung Galaxy S10
Conexión: Wi-Fi

*Impacto de la Solución:*
La usabilidad del campo de contraseña se ha mejorado, permitiendo a los usuarios alternar entre mostrar y ocultar la contraseña. Esto reduce la probabilidad de errores de entrada y mejora la experiencia del usuario.

*Etiquetas:*
#Funcional #Usabilidad #UI #PasswordVisibility #ManualTesting #Seguridad

*Comentarios Finales:*
Este bug ha sido resuelto satisfactoriamente. La funcionalidad del ícono del ojo ya está operativa y fue aprobada por el equipo de QA. Se recomienda mantener esta funcionalidad en futuras versiones y documentar su lógica en el manual de desarrollo.

Fecha de Cierre: 02/11/24
Cerrado por: Milena Gimenez
