### ISSUE TITLE
TC036 Verificar el botón "Volver Atrás" en la sección de edición de perfil

### ISSUE THREAD

**Issue by TauTech99** [ISPC-2024-GrupoEstudio/GrupoEstudio-Mobile2024#131]
**Reporte de Bug 005**
ID del Bug: BUG-TC036-005
Título: El botón "Volver Atrás" no está implementado en la sección de Editar Perfil.
Severidad: Media
Prioridad: Alta
Estado: Abierto
Versión Afectada: v1.0
Fecha del Informe: 30/10/2024
Reportado por: Taoufik Saidi

**Descripción del Problema:**
En la sección de Editar Perfil de la aplicación, se detectó la ausencia del botón "Volver Atrás". Esta falta afecta la navegación del usuario al no permitirle regresar fácilmente a la sección anterior o al menú principal, lo que puede generar confusión y afectar la experiencia de usuario.

**Pasos para Reproducir:**

1. Iniciar la aplicación móvil Pet Boutique.
2. Navegar a la sección Perfil.
3. Seleccionar la opción Editar Perfil.
4. Intentar localizar el botón "Volver Atrás" en la interfaz de la sección.
5. Comprobar si el botón está presente y es funcional.

**Resultado Esperado:**
El botón "Volver Atrás" debería estar visible y funcional en la sección de Editar Perfil, permitiendo al usuario regresar fácilmente a la sección anterior o al menú principal.

**Resultado Real:**
El botón "Volver Atrás" no está presente en la interfaz, lo que impide al usuario retornar a la sección anterior desde Editar Perfil.

**Evidencia:**

**Entorno**:
Sistema Operativo: Android 14
Versión de la App: v1.0
Dispositivo: Samsung Galaxy S10
Conexión: Wi-Fi
**Posible Impacto:**
La falta de un botón de retroceso afecta la navegación y la experiencia del usuario, generando dificultad para regresar a otras secciones sin salir de la pantalla de Editar Perfil. Esto puede disminuir la satisfacción del usuario y su percepción de usabilidad de la aplicación.

**Etiquetas:**
#Funcional #UI #Usabilidad #Navegación #EditarPerfil #ManualTesting

**Comentarios:**
Se recomienda verificar que el botón "Volver Atrás" esté implementado correctamente en todos los dispositivos y resoluciones, y que funcione según lo esperado.

**Comment by ValeAngeletti** [comment]
Informe de Resolución de Bug 005

ID del Bug: BUG-TC036-005
Título: El botón "Volver Atrás" no está implementado en la sección de Editar Perfil
Estado: Cerrado
Fecha de Resolución: 31/10/2024
Resuelto por: Valentina Angeletti

Descripción del Problema:
En la sección de Editar Perfil de la aplicación, se observó la ausencia del botón "Volver Atrás", lo que dificulta la navegación del usuario al no contar con una manera clara de regresar a la pantalla anterior o al menú principal. Esta falta de funcionalidad afecta la experiencia del usuario, generando confusión y una percepción de navegación limitada.

Causa Raíz:
La implementación inicial de la interfaz de Editar Perfil no incluyó el botón de retroceso, lo que impide al usuario regresar fácilmente. Este fallo en el diseño de la interfaz fue causado por una omisión en los requisitos de la pantalla de edición de perfil.

Acciones Tomadas:
Adición del Botón "Volver Atrás" en la Interfaz:
Se agregó un botón de retroceso en la barra de herramientas de la pantalla de Editar Perfil.
El botón se implementó usando los componentes estándar de navegación de Android Studio en Java, asegurando su compatibilidad con la arquitectura de la aplicación.
Funcionalidad de Navegación:
Se programó el botón para que, al hacer clic, lleve al usuario de regreso a la sección anterior o al menú principal.
Se incluyó una verificación para asegurar que el botón funcione de manera consistente en diferentes resoluciones de pantalla y dispositivos.
Pruebas de Navegación y UI:
Se realizaron pruebas en varios dispositivos Android para validar que el botón es visible y funcional en diferentes resoluciones y tamaños de pantalla.
Se probó el flujo de navegación para confirmar que el usuario puede regresar sin problemas desde Editar Perfil a la pantalla de Perfil o el menú principal.
Actualización de la Aplicación:
Se liberó una actualización de la aplicación que incluye el botón de retroceso en la pantalla de Editar Perfil.

Resultados de la Prueba:
Caso Positivo:
El botón "Volver Atrás" es visible y permite al usuario regresar sin problemas a la pantalla anterior.
La navegación es fluida y se ajusta correctamente a diversas resoluciones de pantalla.


Evidencia:
Se adjuntan capturas de pantalla que muestran:
La pantalla de Editar Perfil con el botón "Volver Atrás" visible en la barra de herramientas.


Entorno de Prueba:
Sistema Operativo: Android 13
Versión de la App: v1.0
Dispositivo: Samsung Galaxy A12
Conexión: Wi-Fi

Impacto de la Solución:
La inclusión del botón de retroceso mejora la experiencia de usuario al:
Facilitar la Navegación: Los usuarios pueden regresar fácilmente a la pantalla de Perfil o el menú principal, lo que reduce la confusión y mejora la usabilidad.
Incrementar la Satisfacción del Usuario: Proporciona una interfaz de usuario más intuitiva, lo que favorece la percepción de la aplicación como fácil de usar y bien estructurada.

Etiquetas:
#Funcional #UI #Usabilidad #Navegación #EditarPerfil #ExperienciaDeUsuario #ManualTesting

Comentarios Finales:
Este bug ha sido solucionado exitosamente. Se recomienda realizar revisiones periódicas de la funcionalidad de navegación para mantener la usabilidad de la aplicación en futuras versiones. Además, se sugiere documentar esta mejora en el manual de diseño para futuras actualizaciones de la interfaz.

Fecha de Cierre: 4/11/2024
Cerrado por: Equipo de QA
