### ISSUE TITLE
TC037 Verificar que la foto de perfil permanezca guardada al navegar entre secciones

### ISSUE THREAD

**Issue by TauTech99** [ISPC-2024-GrupoEstudio/GrupoEstudio-Mobile2024#132]
**Reporte de Bug 006**
**ID del Bug: BUG-TC037-006**
Título: La foto de perfil no permanece guardada al navegar entre secciones.
Severidad: Media
Prioridad: Alta
Estado: Abierto
Versión Afectada: v1.0
Fecha del Informe: 30/10/2024
Reportado por: Taoufik Saidi

**Descripción del Problema:**
Después de agregar una foto de perfil en la sección Editar Perfil y guardar los cambios, la foto de perfil no permanece guardada al navegar entre diferentes secciones de la aplicación. El nombre de usuario, sin embargo, se conserva correctamente. Esta inconsistencia afecta la experiencia del usuario al no mantener los datos visuales de su perfil de manera persistente.

**Pasos para Reproducir:**

1. Iniciar la aplicación móvil Pet Boutique.
2. Navegar a la sección Perfil.
3. Seleccionar la opción Editar Perfil.
4. Agregar o actualizar la foto de perfil seleccionando una imagen desde la galería del dispositivo.
5. Guardar los cambios realizados.
6. Navegar a otra sección de la aplicación, como Productos o Carrito.
7. Regresar nuevamente a la sección Perfil.
8. Verificar si la foto de perfil agregada sigue visible y guardada.

**Resultado Esperado:**
La foto de perfil debería permanecer visible en la sección Perfil después de guardar los cambios y debería mantenerse guardada correctamente, incluso al cambiar entre secciones o al regresar al menú de navegación.

**Resultado Real:**
La foto de perfil no se mantiene guardada y no es visible al regresar a la sección Perfil después de navegar a otras secciones. Sin embargo, el nombre de usuario permanece guardado correctamente.

Evidencia:
----

**Entorno:**
Sistema Operativo: Android 14
Versión de la App: v1.0
Dispositivo: Samsung Galaxy S10
Conexión: Wi-Fi
**Posible Impacto:**
La falta de persistencia en la foto de perfil afecta la consistencia visual del perfil de usuario y puede generar confusión o frustración, disminuyendo la confianza del usuario en la aplicación al ver que ciertos cambios no se guardan correctamente.

**Etiquetas**:
#Funcional #UI #Usabilidad #EditarPerfil #Navegación #Persistencia

**Comentarios**:
Se recomienda realizar pruebas adicionales para verificar la persistencia de la foto de perfil después de cerrar y volver a iniciar sesión, y en diferentes dispositivos o plataformas para identificar si el problema es específico de un entorno o dispositivo.

**Comment by ValeAngeletti** [comment]
Informe de Resolución de Bug 006

ID del Bug: BUG-TC037-006
Título: La foto de perfil no permanece guardada al navegar entre secciones
Estado: Cerrado
Fecha de Resolución: 06/11/2024
Resuelto por: Valentina Angeletti


Descripción del Problema:
Después de agregar una foto de perfil en la sección Editar Perfil y guardar los cambios, la foto de perfil no permanecía guardada al navegar entre diferentes secciones de la aplicación. Esta inconsistencia afectaba la experiencia del usuario al no mantener los datos visuales de su perfil de manera persistente.

Causa Raíz:
El problema surgió debido a que la foto de perfil no se actualizaba correctamente en la base de datos. La aplicación no estaba recuperando y mostrando la imagen guardada al regresar a la sección Perfil.

Acciones Tomadas:

- Actualización de la Base de Datos: Se implementó un proceso para asegurar que la foto de perfil se actualice correctamente en la base de datos al guardar los cambios.
- Recuperación de Datos: Se modificó la lógica de la aplicación para que recupere y muestre la foto de perfil desde la base de datos cada vez que el usuario accede a la sección Perfil.
- Pruebas Manuales: Se realizaron pruebas manuales para verificar que la foto de perfil se mantenga visible y guardada al navegar entre diferentes secciones de la aplicación.

Resultados de la Prueba:

- Caso Positivo:
    - Al guardar una nueva foto de perfil, esta permanece visible y guardada al navegar entre secciones y al regresar a la sección Perfil.

Entorno de Prueba:

    Versión de la App: v1.0
    Dispositivo: Samsung Galaxy A12
    Conexión: Wi-Fi

Impacto de la Solución:
La solución implementada asegura que la foto de perfil se mantenga persistente y visible, mejorando la consistencia visual del perfil de usuario y la confianza en la aplicación al garantizar que los cambios se guardan correctamente.

Etiquetas:
#Funcional #UI #Usabilidad #EditarPerfil #Navegación #Persistencia

Comentarios Finales:
El bug ha sido resuelto de forma satisfactoria. La funcionalidad de persistencia de la foto de perfil está operativa y ha sido aprobada por el equipo de QA. Se recomienda documentar este proceso de actualización y recuperación de datos en el manual de desarrollo para futuras referencias.

Fecha de Cierre: 06/11/2024
Cerrado por: Valentina Angeletti
