### ISSUE TITLE
TC006 Registro de Usuario con datos invalidos(Negativo)

### ISSUE THREAD

**Issue by TauTech99** [ISPC-2024-GrupoEstudio/GrupoEstudio-Mobile2024#59]
#12 

**Reporte** de Bug 1

- [ ] -Título: El sistema permite el registro de usuario con datos inválidos

- Nombre del tester: Saidi Taoufik

-  Fecha: 18/09/2024

- Aplicación y versión:

- Aplicación: Pet Boutique App

- Versión: 1.0

- Ambiente del Tester:

 Sistema Operativo: Android (versión 14)

Dispositivo: Samsung Galaxy S21

- Conexión a internet: Estable

- [ ] Descripción del problema:

Al intentar registrar un usuario con datos inválidos en la aplicación, el sistema permite completar el registro de manera exitosa en lugar de mostrar mensajes de error indicando la invalidez de los datos ingresados. Esto incluye nombres numéricos, DNIs demasiado largos, 

- [ ] Impacto:

Este fallo puede permitir que usuarios ingresen datos incorrectos en la base de datos, lo que compromete la integridad de la información y causa confusión en la experiencia de usuario. Además, puede generar datos corruptos o inservibles, afectando el análisis y la gestión de los usuarios en la plataforma.

- [ ] Pasos para reproducir el bug:

Acceder a la sección de registro de la aplicación móvil.
Ingresar los siguientes datos inválidos:
Nombre: 7777
Apellido: 7777
Correo electrónico: dolor@gmail.com
DNI: 99999999999999
Contraseña: *********
Confirmar Contraseña: ********
Hacer clic en el botón de registro.
El sistema permite completar el registro exitosamente, mostrando el mensaje "Registro exitoso" en lugar de advertir sobre los datos inválidos.

- [ ] Resultado obtenido:

El registro se completa con éxito a pesar de que los datos ingresados son inválidos, como un nombre numérico, un DNI de longitud incorrecta

- [ ] Resultado esperado:

El sistema debería validar los datos ingresados y mostrar mensajes de error específicos para cada campo inválido (por ejemplo, nombre con caracteres numéricos, DNI demasiado largo, ) y no permitir que el registro se complete.
Prioridad: Crítica

- [ ] Captura de pantalla:

![Image](https://github.com/user-attachments/assets/9f3eb2a0-bce2-4dcb-a8f3-13e2039752d6)

**Comment by MilenaGimenez** [comment]
Estado: Resuelto

    Fecha de resolución: [22/10/2024]

    Descripción de la solución:
    Se implementaron validaciones adicionales para los campos de nombre, apellido, DNI y correo electrónico. Ahora el sistema:
        Rechaza nombres y apellidos con caracteres numéricos.
        Valida la longitud del DNI.
        Muestra mensajes de error específicos para cada campo inválido, impidiendo que el registro se complete con datos incorrectos.

Pruebas de validación realizadas:

    Se verificó que el registro con datos inválidos no se completa.
    Mensajes de error adecuados aparecen para cada campo incorrecto.
    El registro con datos válidos se realiza correctamente.

Impacto de la solución:

Este cambio asegura que solo se registren datos válidos, mejorando la integridad de la información en la base de datos y optimizando la experiencia del usuario.
Estado final:

✅ Cerrado. El bug ha sido solucionado

https://drive.google.com/drive/folders/1OkS8t5r_dYgEpAC-ii3E8YlxRkj-iW2D
